# Generated by Django 3.2.25 on 2024-05-27 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rocketapi', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpfcnpj', models.CharField(max_length=14)),
                ('payee_type', models.CharField(choices=[('C', 'Company'), ('P', 'Person')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='object_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rocketapi.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('S', 'Scheduled'), ('P', 'Processing'), ('P', 'Paid'), ('R', 'Rejected')], default='P', max_length=1),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='account',
            name='payee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rocketapi.payee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rocketapi.payee'),
            preserve_default=False,
        ),
    ]
