# Generated by Django 3.2.25 on 2024-05-28 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rocketapi', '0005_auto_20240527_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payees', to=settings.AUTH_USER_MODEL),
        ),
    ]
