# Generated by Django 5.0.6 on 2024-05-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocketapi', '0006_alter_payee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('S', 'Scheduled'), ('P', 'Paid'), ('R', 'Rejected')], default='S', max_length=1),
        ),
    ]
